default_platform(:android)

FIREBASE_APP_ID_ANDROID = "1:662621136369:android:a2220fcdbabb7c28079050"
FIREBASE_APP_ID_IOS = "1:662621136369:ios:90753c3b7e3d242b079050"

BUNDLE_ID_IOS = "com.jello.jellomark"

platform :android do
  desc "Distribute Android app via Firebase App Distribution"
  lane :distribute do
    firebase_app_distribution(
      app: FIREBASE_APP_ID_ANDROID,
      apk_path: "build/app/outputs/flutter-apk/app-release.apk",
      service_credentials_file: ENV["FIREBASE_SERVICE_ACCOUNT_KEY_PATH"],
      groups: "testers"
    )
  end

  desc "Upload Android App Bundle to Play Store Internal Testing"
  lane :play_internal do
    upload_to_play_store(
      package_name: "com.jello.jellomark",
      track: "internal",
      aab: "build/app/outputs/bundle/release/app-release.aab",
      json_key: ENV["PLAY_STORE_JSON_KEY_PATH"],
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      release_status: "completed"
    )
  end
end

platform :ios do
  desc "Distribute iOS app via Firebase App Distribution"
  lane :distribute do
    setup_ci if ENV["CI"]

    build_app(
      workspace: "ios/Runner.xcworkspace",
      scheme: "Runner",
      configuration: "Release",
      export_method: "ad-hoc",
      output_directory: "build/ios",
      output_name: "Runner.ipa",
      xcargs: "-allowProvisioningUpdates",
      export_options: {
        signingStyle: "manual",
        provisioningProfiles: {
          BUNDLE_ID_IOS => "#{BUNDLE_ID_IOS} AdHoc"
        }
      }
    )

    firebase_app_distribution(
      app: FIREBASE_APP_ID_IOS,
      ipa_path: "build/ios/Runner.ipa",
      service_credentials_file: ENV["FIREBASE_SERVICE_ACCOUNT_KEY_PATH"],
      groups: "testers"
    )
  end

  desc "Upload iOS build to TestFlight Internal Testing"
  lane :appstore_internal do
    setup_ci if ENV["CI"]

    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY"]
    )

    build_app(
      workspace: "ios/Runner.xcworkspace",
      scheme: "Runner",
      configuration: "Release",
      export_method: "app-store",
      output_directory: "build/ios",
      output_name: "Runner.ipa",
      xcargs: "-allowProvisioningUpdates CODE_SIGN_STYLE=Manual PROVISIONING_PROFILE_SPECIFIER='#{BUNDLE_ID_IOS} AppStore' CODE_SIGN_IDENTITY='Apple Distribution' DEVELOPMENT_TEAM=473NP427RC",
      export_options: {
        signingStyle: "manual",
        provisioningProfiles: {
          BUNDLE_ID_IOS => "#{BUNDLE_ID_IOS} AppStore"
        }
      }
    )

    upload_to_testflight(
      api_key: api_key,
      ipa: "build/ios/Runner.ipa",
      skip_waiting_for_build_processing: true
    )
  end
end
