default_platform(:android)

FIREBASE_APP_ID_ANDROID = "1:662621136369:android:a2220fcdbabb7c28079050"
FIREBASE_APP_ID_IOS = "1:662621136369:ios:90753c3b7e3d242b079050"

platform :android do
  desc "Distribute Android app via Firebase App Distribution"
  lane :distribute do
    firebase_app_distribution(
      app: FIREBASE_APP_ID_ANDROID,
      apk_path: "build/app/outputs/flutter-apk/app-release.apk",
      service_credentials_file: ENV["FIREBASE_SERVICE_ACCOUNT_KEY_PATH"],
      groups: "testers"
    )
  end
end

platform :ios do
  desc "Distribute iOS app via Firebase App Distribution"
  lane :distribute do
    setup_ci if ENV["CI"]

    build_app(
      workspace: "ios/Runner.xcworkspace",
      scheme: "Runner",
      configuration: "Release",
      export_method: "ad-hoc",
      output_directory: "build/ios",
      output_name: "Runner.ipa",
      xcargs: "-allowProvisioningUpdates",
      export_options: {
        signingStyle: "manual",
        provisioningProfiles: {
          "com.jello.jellomark" => "com.jello.jellomark AdHoc"
        }
      }
    )

    firebase_app_distribution(
      app: FIREBASE_APP_ID_IOS,
      ipa_path: "build/ios/Runner.ipa",
      service_credentials_file: ENV["FIREBASE_SERVICE_ACCOUNT_KEY_PATH"],
      groups: "testers"
    )
  end
end
